version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      # Add your backend environment variables here
      NODE_ENV: production
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      # Add your frontend environment variables here
    volumes:
      - ./frontend:/app

networks:
  default:
    driver: bridge
